// Code generated by bpf2go; DO NOT EDIT.
//go:build arm64

package tracer

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type tracerConfig struct {
	_         structs.HostLayout
	TargetPid int32
}

type tracerEvent struct {
	_               structs.HostLayout
	Type            tracerEventType
	Comm            [16]uint8
	_               [7]byte
	Ts              uint64
	ProcessIdentity struct {
		_         structs.HostLayout
		Pid       uint32
		Tid       uint32
		StartTime uint64
	}
	CgroupId uint64
	NsPid    uint32
	NsTid    uint32
}

type tracerEventType uint8

const (
	tracerEventTypeUNKNOWN        tracerEventType = 0
	tracerEventTypeFORK           tracerEventType = 1
	tracerEventTypeEXEC           tracerEventType = 2
	tracerEventTypeEXIT           tracerEventType = 3
	tracerEventTypeMAX_EVENT_TYPE tracerEventType = 4
)

type tracerForkEvent struct {
	_      structs.HostLayout
	Event  tracerEvent
	Parent struct {
		_         structs.HostLayout
		Pid       uint32
		Tid       uint32
		StartTime uint64
	}
}

// loadTracer returns the embedded CollectionSpec for tracer.
func loadTracer() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_TracerBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load tracer: %w", err)
	}

	return spec, err
}

// loadTracerObjects loads tracer and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*tracerObjects
//	*tracerPrograms
//	*tracerMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadTracerObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadTracer()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// tracerSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tracerSpecs struct {
	tracerProgramSpecs
	tracerMapSpecs
	tracerVariableSpecs
}

// tracerProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tracerProgramSpecs struct {
	SchedProcessExec *ebpf.ProgramSpec `ebpf:"sched_process_exec"`
	SchedProcessExit *ebpf.ProgramSpec `ebpf:"sched_process_exit"`
	SchedProcessFork *ebpf.ProgramSpec `ebpf:"sched_process_fork"`
	Trigger          *ebpf.ProgramSpec `ebpf:"trigger"`
}

// tracerMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tracerMapSpecs struct {
	Events      *ebpf.MapSpec `ebpf:"events"`
	TailCallMap *ebpf.MapSpec `ebpf:"tail_call_map"`
}

// tracerVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tracerVariableSpecs struct {
	Conf            *ebpf.VariableSpec `ebpf:"conf"`
	UnusedEvent     *ebpf.VariableSpec `ebpf:"unused_event"`
	UnusedForkEvent *ebpf.VariableSpec `ebpf:"unused_fork_event"`
}

// tracerObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadTracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type tracerObjects struct {
	tracerPrograms
	tracerMaps
	tracerVariables
}

func (o *tracerObjects) Close() error {
	return _TracerClose(
		&o.tracerPrograms,
		&o.tracerMaps,
	)
}

// tracerMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadTracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type tracerMaps struct {
	Events      *ebpf.Map `ebpf:"events"`
	TailCallMap *ebpf.Map `ebpf:"tail_call_map"`
}

func (m *tracerMaps) Close() error {
	return _TracerClose(
		m.Events,
		m.TailCallMap,
	)
}

// tracerVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadTracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type tracerVariables struct {
	Conf            *ebpf.Variable `ebpf:"conf"`
	UnusedEvent     *ebpf.Variable `ebpf:"unused_event"`
	UnusedForkEvent *ebpf.Variable `ebpf:"unused_fork_event"`
}

// tracerPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadTracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type tracerPrograms struct {
	SchedProcessExec *ebpf.Program `ebpf:"sched_process_exec"`
	SchedProcessExit *ebpf.Program `ebpf:"sched_process_exit"`
	SchedProcessFork *ebpf.Program `ebpf:"sched_process_fork"`
	Trigger          *ebpf.Program `ebpf:"trigger"`
}

func (p *tracerPrograms) Close() error {
	return _TracerClose(
		p.SchedProcessExec,
		p.SchedProcessExit,
		p.SchedProcessFork,
		p.Trigger,
	)
}

func _TracerClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed tracer_arm64_bpfel.o
var _TracerBytes []byte
